# Generated by Django 4.2.6 on 2023-10-13 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secquestions0', models.CharField(choices=[('Q0', '¿Cuál es el lugar que más quieres visitar?'), ('Q1', '¿Cuál es el nombre de tu primera mascota?'), ('Q2', '¿En qué ciudad naciste?'), ('Q3', '¿Cuál es tu película favorita?'), ('Q4', '¿Qué deporte practicas o te gusta más?'), ('Q5', '¿Cuál es el nombre de tu mejor amigo/a de la infancia?'), ('Q6', '¿Cuál es el nombre del primer libro que leíste?'), ('Q7', '¿Qué comida te gusta más?'), ('Q8', '¿Cuál es el apellido de soltera de tu madre?'), ('Q9', '¿Qué instrumento musical sabes tocar o te gustaría aprender?')], default='Q0', max_length=2, verbose_name='Preguntas de Seguridad')),
                ('secanwser0', models.TextField(verbose_name='Respuesta 1')),
                ('secquestions1', models.CharField(choices=[('Q0', '¿Cuál es el lugar que más quieres visitar?'), ('Q1', '¿Cuál es el nombre de tu primera mascota?'), ('Q2', '¿En qué ciudad naciste?'), ('Q3', '¿Cuál es tu película favorita?'), ('Q4', '¿Qué deporte practicas o te gusta más?'), ('Q5', '¿Cuál es el nombre de tu mejor amigo/a de la infancia?'), ('Q6', '¿Cuál es el nombre del primer libro que leíste?'), ('Q7', '¿Qué comida te gusta más?'), ('Q8', '¿Cuál es el apellido de soltera de tu madre?'), ('Q9', '¿Qué instrumento musical sabes tocar o te gustaría aprender?')], default='Q0', max_length=2, verbose_name='Preguntas de Seguridad')),
                ('secanwser1', models.TextField(verbose_name='Respuesta 2')),
                ('secquestions2', models.CharField(choices=[('Q0', '¿Cuál es el lugar que más quieres visitar?'), ('Q1', '¿Cuál es el nombre de tu primera mascota?'), ('Q2', '¿En qué ciudad naciste?'), ('Q3', '¿Cuál es tu película favorita?'), ('Q4', '¿Qué deporte practicas o te gusta más?'), ('Q5', '¿Cuál es el nombre de tu mejor amigo/a de la infancia?'), ('Q6', '¿Cuál es el nombre del primer libro que leíste?'), ('Q7', '¿Qué comida te gusta más?'), ('Q8', '¿Cuál es el apellido de soltera de tu madre?'), ('Q9', '¿Qué instrumento musical sabes tocar o te gustaría aprender?')], default='Q0', max_length=2, verbose_name='Preguntas de Seguridad')),
                ('secanwser2', models.TextField(verbose_name='Respuesta 3')),
                ('From_User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='De Usuario')),
            ],
        ),
    ]
