# Generated by Django 4.2.6 on 2023-10-13 07:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preguntas',
            new_name='Questions',
        ),
    ]
