# Generated by Django 4.2.6 on 2023-10-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_preguntas_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
