# Generated by Django 4.2.6 on 2023-11-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_entries_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='otp',
            field=models.TextField(blank=True, max_length=6, null=True),
        ),
    ]
