# Generated by Django 4.2.6 on 2023-10-13 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0003_questions_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='From_User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questions',
            name='secanwser0',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='secanwser1',
            field=models.TextField(verbose_name='Anwser 2'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='secanwser2',
            field=models.TextField(verbose_name='Anwser 3'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='secquestions0',
            field=models.CharField(choices=[('Q0', 'Place you want to visit.'), ('Q1', 'Name of your first pet.'), ('Q2', 'City were you born.'), ('Q3', 'Favorite Movie.'), ('Q4', 'Sport you practice or like the most.'), ('Q5', 'Name of your best childhood friend.'), ('Q6', 'Name of the first book you read.'), ('Q7', 'Food you prefer.'), ('Q8', "Your mother's maiden name."), ('Q9', 'Musical instrument you know how to play or would like to learn.')], default='Q0', max_length=2),
        ),
        migrations.AlterField(
            model_name='questions',
            name='secquestions1',
            field=models.CharField(choices=[('Q0', 'Place you want to visit.'), ('Q1', 'Name of your first pet.'), ('Q2', 'City were you born.'), ('Q3', 'Favorite Movie.'), ('Q4', 'Sport you practice or like the most.'), ('Q5', 'Name of your best childhood friend.'), ('Q6', 'Name of the first book you read.'), ('Q7', 'Food you prefer.'), ('Q8', "Your mother's maiden name."), ('Q9', 'Musical instrument you know how to play or would like to learn.')], default='Q0', max_length=2),
        ),
        migrations.AlterField(
            model_name='questions',
            name='secquestions2',
            field=models.CharField(choices=[('Q0', 'Place you want to visit.'), ('Q1', 'Name of your first pet.'), ('Q2', 'City were you born.'), ('Q3', 'Favorite Movie.'), ('Q4', 'Sport you practice or like the most.'), ('Q5', 'Name of your best childhood friend.'), ('Q6', 'Name of the first book you read.'), ('Q7', 'Food you prefer.'), ('Q8', "Your mother's maiden name."), ('Q9', 'Musical instrument you know how to play or would like to learn.')], default='Q0', max_length=2),
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secquestions0', models.CharField(choices=[('Q0', 'Lugar que quieres visitar.'), ('Q1', 'Nombre de tu primera mascota'), ('Q2', 'Ciudad donde naciste'), ('Q3', 'Pelicula Favorita.'), ('Q4', 'Deporte que practicas o te gusta más.'), ('Q5', 'Nombre de tu mejor amigo de la infancia.'), ('Q6', 'Nombre del primer libro que leíste.'), ('Q7', 'Comida que prefieres.'), ('Q8', 'Apellido de soltera de tu madre.'), ('Q9', 'Instrumento musical que sabes tocar o te gustaría aprender.')], default='Q0', max_length=2)),
                ('secanwser0', models.TextField(verbose_name='Anwser 1')),
                ('secquestions1', models.CharField(choices=[('Q0', 'Lugar que quieres visitar.'), ('Q1', 'Nombre de tu primera mascota'), ('Q2', 'Ciudad donde naciste'), ('Q3', 'Pelicula Favorita.'), ('Q4', 'Deporte que practicas o te gusta más.'), ('Q5', 'Nombre de tu mejor amigo de la infancia.'), ('Q6', 'Nombre del primer libro que leíste.'), ('Q7', 'Comida que prefieres.'), ('Q8', 'Apellido de soltera de tu madre.'), ('Q9', 'Instrumento musical que sabes tocar o te gustaría aprender.')], default='Q0', max_length=2)),
                ('secanwser1', models.TextField(verbose_name='Anwser 2')),
                ('secquestions2', models.CharField(choices=[('Q0', 'Lugar que quieres visitar.'), ('Q1', 'Nombre de tu primera mascota'), ('Q2', 'Ciudad donde naciste'), ('Q3', 'Pelicula Favorita.'), ('Q4', 'Deporte que practicas o te gusta más.'), ('Q5', 'Nombre de tu mejor amigo de la infancia.'), ('Q6', 'Nombre del primer libro que leíste.'), ('Q7', 'Comida que prefieres.'), ('Q8', 'Apellido de soltera de tu madre.'), ('Q9', 'Instrumento musical que sabes tocar o te gustaría aprender.')], default='Q0', max_length=2)),
                ('secanwser2', models.TextField(verbose_name='Anwser 3')),
                ('encrypted', models.BooleanField(default=False)),
                ('From_User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
