# Generated by Django 4.2.6 on 2023-10-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_questions_from_user_alter_questions_secanwser0_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preguntas',
        ),
    ]
